version: 2

sphinx:
  configuration: docs/conf.py

formats:
  - html

# Optionally set the version of Python and requirements required to build your docs
python:
  version: 3.7
  install:
    - requirements: docs/requirements.txt
