dist: xenial
language: python
python:
  - 3.6
  - 3.7
cache:
  directories:
    - $HOME/.cache/pip

before_install:
  - pip install flit

install:
  - flit install
  - pip install pytest coverage codecov flake8

script:
  - coverage run --source=frappuccino -m pytest
  - coverage report -m
  - codecov
  - flake8
